### ISSUE TITLE
Creates an RSS feed only when the container is started or restarted.

### ISSUE THREAD

**Issue by VlaK0r** [h33n0k/nl2rss#5]
Hello! 
Thank you for your work!

You've made a very useful tool, but it doesn't work properly.
Creates an RSS feed only when the container is started or restarted. If you do not restart the container, the RSS feed will not be created from new email.

In order for the program to work until the cause of the malfunction is found, I added a "restarter" container that restarts the "nl2rss" container every 10 minutes.

```
  restarter:
    image: docker:cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - /bin/sh
      - -c
      - while true; do sleep 600; docker restart nl2rss; done
    restart: unless-stopped
```
To detect the error, I am ready to provide any data and logs.
